schema_version: 1
kind: package
name: rcl-logging-spdlog
version: 3.1.1
versions:
  - 3.1.1
default_version: 3.1.1
type: library
category: ROS 2
description: spdlog backend for rcl logging
depends:
  - rcl-logging-interface
  - rcpputils
  - rcutils
  - spdlog
  - spdlog-vendor
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rcl_logging-release/archive/release/jazzy/rcl_logging_spdlog/3.1.1-1.tar.gz
  archive: rcl_logging_spdlog-3.1.1-1.tar.gz
  sha256: 22694be0a15c333c62a2ca2eb146f8d06791724085a42bb4f3e272edd2cb742b
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/lib
      - /usr/share
install:
  libraries:
    - usr/lib
