schema_version: 1
kind: package
name: rcl-logging-interface
version: 3.1.1
versions:
  - 3.1.1
default_version: 3.1.1
type: library
category: ROS 2
description: rcl logging plugin interface
depends:
  - rcutils
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rcl_logging-release/archive/release/jazzy/rcl_logging_interface/3.1.1-1.tar.gz
  archive: rcl_logging_interface-3.1.1-1.tar.gz
  sha256: c0a3490f83a7a12d284619daf4eeb1050855fa989db6e80f8036bb117913a346
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/include
      - /usr/lib
      - /usr/share
install:
  headers:
    - usr/include
  libraries:
    - usr/lib
