schema_version: 1
kind: package
name: rcl
version: 9.2.7
versions:
  - 9.2.7
default_version: 9.2.7
type: library
category: ROS 2
description: ROS 2 C client library
depends:
  - libyaml-vendor
  - rcl-interfaces
  - rcl-logging-interface
  - rcl-logging-spdlog
  - rcl-yaml-param-parser
  - rcutils
  - rmw
  - rmw-implementation
  - rosidl-runtime-c
  - service-msgs
  - tracetools
  - type-description-interfaces
  - libyaml
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rcl-release/archive/release/jazzy/rcl/9.2.7-1.tar.gz
  archive: rcl-9.2.7-1.tar.gz
  sha256: c7f0fb33c4c0a9b48489514679abfcc9a45ea2072aae9ccbfb95e0319eb65b05
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/include
      - /usr/lib
      - /usr/share
    cmake_args:
      - -DCMAKE_C_FLAGS=-D_GNU_SOURCE
install:
  headers:
    - usr/include
  libraries:
    - usr/lib
