from .package_metadata import (
    load_all_package_metadata,
    package_option_choice_symbol,
    package_option_symbol,
    package_symbol,
    package_version_symbol,
)


GENERATED_HEADER = "# Generated by smart-build package metadata. Do not edit by hand.\n\n"
INDEX_HEADER = "# Generated by smart-build package metadata. Do not edit by hand.\n\n"


def generate_package_kconfig_files(root):
    packages = sorted(load_all_package_metadata(root), key=lambda item: item.name)
    provider_map = _provider_map(packages)
    result = {}
    for metadata in packages:
        relative_path = f"packages/{metadata.name}/Kconfig"
        result[relative_path] = _package_kconfig(metadata, provider_map)
    return result


def generate_package_kconfig_index(root):
    packages = sorted(load_all_package_metadata(root), key=lambda item: item.name)
    lines = [INDEX_HEADER.rstrip(), ""]
    for metadata in packages:
        lines.append(f'source "packages/{metadata.name}/Kconfig"')
    return "\n".join(lines).rstrip() + "\n"


def _package_kconfig(metadata, provider_map):
    return GENERATED_HEADER + "\n".join(_package_lines(metadata, provider_map)).rstrip() + "\n"


def _package_lines(metadata, provider_map):
    symbol = package_symbol(metadata.name)
    lines = [
        f"menu \"{metadata.name}\"",
        "",
        f"config {symbol}",
        f"    bool \"{metadata.name}\"",
    ]
    selected_symbols = {
        symbol
        for selected in metadata.selects
        for symbol in [_provided_dependency_symbol(metadata, selected, provider_map)]
        if symbol is not None
    }
    if metadata.depends:
        for dependency in metadata.depends:
            dependency_symbol = _provided_dependency_symbol(metadata, dependency, provider_map)
            if dependency_symbol is not None and dependency_symbol not in selected_symbols:
                lines.append(f"    depends on {dependency_symbol}")
    for selected_symbol in sorted(selected_symbols):
        lines.append(f"    select {selected_symbol}")
    for conflict in metadata.conflicts:
        lines.append(f"    depends on !{package_symbol(conflict)}")
    lines.append("")
    lines.extend(_version_lines(metadata, symbol))
    for option in metadata.options:
        lines.extend(_option_lines(metadata.name, symbol, option))
    lines.append("endmenu")
    return lines


def _version_lines(metadata, package_config):
    lines = []
    if len(metadata.versions) > 1:
        lines.extend(
            [
                "choice",
                f"    prompt \"{metadata.name} version\"",
                f"    depends on {package_config}",
                f"    default {package_version_symbol(metadata.name, metadata.default_version)}",
                "",
            ]
        )
        for version in metadata.versions:
            lines.extend(
                [
                    f"config {package_version_symbol(metadata.name, version)}",
                    f"    bool \"{version}\"",
                    "",
                ]
            )
        lines.extend(["endchoice", ""])
    lines.extend(
        [
            f"config {package_config}_VERSION",
            "    string",
            f"    depends on {package_config}",
        ]
    )
    if len(metadata.versions) > 1:
        for version in metadata.versions:
            lines.append(f"    default \"{version}\" if {package_version_symbol(metadata.name, version)}")
    lines.append(f"    default \"{metadata.default_version}\"")
    lines.append("")
    return lines


def _option_lines(package_name, package_config, option):
    symbol = package_option_symbol(package_name, option.name)
    if option.type == "bool":
        return [
            f"config {symbol}",
            f"    bool \"{option.prompt}\"",
            f"    depends on {package_config}",
            *(['    default y'] if option.default else []),
            "",
        ]
    if option.type == "string":
        return [
            f"config {symbol}",
            f"    string \"{option.prompt}\"",
            f"    depends on {package_config}",
            f"    default \"{_escape_string(option.default)}\"",
            "",
        ]
    return _choice_option_lines(package_name, package_config, option, symbol)


def _choice_option_lines(package_name, package_config, option, symbol):
    lines = [
        "choice",
        f"    prompt \"{option.prompt}\"",
        f"    depends on {package_config}",
        f"    default {package_option_choice_symbol(package_name, option.name, option.default)}",
        "",
    ]
    for choice in option.choices:
        lines.extend(
            [
                f"config {package_option_choice_symbol(package_name, option.name, choice)}",
                f"    bool \"{choice}\"",
                "",
            ]
        )
    lines.extend(
        [
            "endchoice",
            "",
            f"config {symbol}",
            "    string",
            f"    depends on {package_config}",
        ]
    )
    for choice in option.choices:
        lines.append(f"    default \"{choice}\" if {package_option_choice_symbol(package_name, option.name, choice)}")
    lines.extend([f"    default \"{option.default}\"", ""])
    return lines


def _provider_map(packages):
    providers = {}
    for package in packages:
        for provided in package.provides:
            providers.setdefault(provided, package.name)
    return providers


def _provided_dependency_symbol(metadata, dependency, provider_map):
    if dependency == metadata.name or dependency in metadata.provides:
        return None
    package_name = provider_map.get(dependency)
    if package_name is None:
        return None
    return package_symbol(package_name)


def _escape_string(value):
    return str(value).replace("\\", "\\\\").replace('"', '\\"')
