schema_version: 1
kind: package
name: rmw-dds-common
version: 3.1.1
versions:
  - 3.1.1
default_version: 3.1.1
type: library
category: ROS 2
description: Common helpers for DDS RMW implementations
depends:
  - rcpputils
  - rcutils
  - rmw
  - rosidl-runtime-c
  - rosidl-runtime-cpp
  - rosidl-default-runtime
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rmw_dds_common-release/archive/release/jazzy/rmw_dds_common/3.1.1-1.tar.gz
  archive: rmw_dds_common-3.1.1-1.tar.gz
  sha256: 5f8c8a8273bc089fdcdee85dbd82ec619beaff1eea65b58db091323d0d2c2bfa
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/include
      - /usr/lib
      - /usr/share
install:
  headers:
    - usr/include
  libraries:
    - usr/lib
