import io
import shutil
from pathlib import Path

import yaml
import pytest

from smart_build.buildroot_import import (
    _existing_owners,
    _write_ownership,
    import_buildroot_packages,
    load_never_import_names,
    parse_buildroot_config,
    run_buildroot_menuconfig,
)
from smart_build.package_kconfig import generate_package_kconfig_index
from smart_build.descriptions import load_description
from smart_build.domains.package_sources import package_source_config
from smart_build.errors import SmartBuildError
from smart_build.package_metadata import normalize_package_metadata
from smart_build.paths import BuildPaths


class _Terminal(io.StringIO):
    def isatty(self):
        return True


def _project(tmp_path):
    buildroot = tmp_path / "buildroot"
    (buildroot / "package" / "foo").mkdir(parents=True)
    (buildroot / "package" / "existing").mkdir(parents=True)
    (buildroot / "Makefile").write_text("all:\n", encoding="utf-8")
    (buildroot / ".config").write_text(
        "BR2_PACKAGE_FOO=y\nBR2_PACKAGE_EXISTING=y\nBR2_PACKAGE_BAD=y\n",
        encoding="utf-8",
    )
    (buildroot / "package" / "foo" / "foo.mk").write_text(
        'FOO_VERSION = 1.2.3\nFOO_SITE = https://example.org/foo\n'
        'FOO_SOURCE = foo-1.2.3.tar.gz\n',
        encoding="utf-8",
    )
    (buildroot / "package" / "foo" / "foo.hash").write_text(
        "sha256 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef foo-1.2.3.tar.gz\n",
        encoding="utf-8",
    )
    (buildroot / "package" / "foo" / "Config.in").write_text(
        'config BR2_PACKAGE_FOO\n'
        '    bool "foo library"\n'
        '    help\n'
        '      A tiny foo library used in import tests\n',
        encoding="utf-8",
    )
    (buildroot / "package" / "existing" / "existing.mk").write_text(
        'EXISTING_VERSION = 1.0\nEXISTING_SITE = https://example.org/existing\n'
        'EXISTING_SOURCE = existing.tar.gz\n',
        encoding="utf-8",
    )
    packages = tmp_path / "packages"
    existing = packages / "existing"
    existing.mkdir(parents=True)
    (existing / "package.yaml").write_text(
        "schema_version: 1\nkind: package\nname: existing\nversion: '1.0'\n"
        "type: executable\nsource:\n  directory: apps/hello\n"
        "build:\n  python:\n    script: sbuild.py\n    outputs: [/bin/existing]\ninstall:\n  path: /bin/existing\n",
        encoding="utf-8",
    )
    (existing / "sbuild.py").write_text("", encoding="utf-8")
    (packages / "Kconfig").write_text("# generated\n", encoding="utf-8")
    paths = BuildPaths.for_machine("test-machine", root=tmp_path)
    return paths


def test_parse_buildroot_config_only_returns_enabled_target_packages(tmp_path):
    config = tmp_path / ".config"
    config.write_text("BR2_PACKAGE_FOO=y\nBR2_PACKAGE_HOST_MAKE=y\n# BR2_PACKAGE_BAR is not set\n", encoding="utf-8")
    assert parse_buildroot_config(config) == ("BR2_PACKAGE_FOO",)


def test_import_is_best_effort_and_keeps_network_source(tmp_path):
    paths = _project(tmp_path)
    console = io.StringIO()
    summary = import_buildroot_packages(paths, console=console)

    assert summary.imported == 1
    assert summary.skipped == 1
    assert summary.failed == 1
    package_dir = tmp_path / "packages" / "foo"
    assert not (package_dir / "source").exists()
    package = yaml.safe_load((package_dir / "package.yaml").read_text(encoding="utf-8"))
    assert package["source"]["url"] == "https://example.org/foo/foo-1.2.3.tar.gz"
    assert package["source"]["sha256"] == "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    assert package["source"]["allow_unverified"] is False
    assert 'source "packages/foo/Kconfig"' in (tmp_path / "packages" / "Kconfig").read_text(encoding="utf-8")
    assert "Buildroot import" not in (package_dir / "Kconfig").read_text(encoding="utf-8")
    assert "# Generated by smart-build package metadata." in (package_dir / "Kconfig").read_text(encoding="utf-8")
    assert package["description"] == "A tiny foo library used in import tests"
    kconfig = (package_dir / "Kconfig").read_text(encoding="utf-8")
    assert 'bool "foo - A tiny foo library used in import tests"' in kconfig
    assert "A tiny foo library used in import tests" in kconfig
    assert "    help" in kconfig
    assert "failed: bad" in console.getvalue()
    metadata = normalize_package_metadata(load_description(package_dir / "package.yaml"))
    assert metadata.name == "foo"
    assert metadata.description == "A tiny foo library used in import tests"


def test_imported_package_remains_buildable_after_buildroot_is_removed(tmp_path):
    paths = _project(tmp_path)
    summary = import_buildroot_packages(paths, package="foo")
    assert summary.failed == 0

    shutil.rmtree(tmp_path / "buildroot")
    description = load_description(tmp_path / "packages" / "foo" / "package.yaml")
    config = package_source_config(paths, "foo", description)

    assert config.url == "https://example.org/foo/foo-1.2.3.tar.gz"
    assert config.archive == tmp_path / "downloads" / "foo-1.2.3.tar.gz"
    assert not (tmp_path / "packages" / "foo" / "sources").exists()


def test_import_progress_uses_colours_on_terminal(tmp_path, monkeypatch):
    paths = _project(tmp_path)
    console = _Terminal()
    monkeypatch.delenv("NO_COLOR", raising=False)
    import_buildroot_packages(paths, package="foo", console=console)
    output = console.getvalue()
    assert "\033[32m" in output
    assert "import: [########################] 1/1 foo" in output


def test_import_allows_network_source_without_hash(tmp_path):
    paths = _project(tmp_path)
    hash_path = tmp_path / "buildroot" / "package" / "foo" / "foo.hash"
    hash_path.unlink()
    summary = import_buildroot_packages(paths, package="foo")
    assert summary.failed == 0
    package = yaml.safe_load(
        (tmp_path / "packages" / "foo" / "package.yaml").read_text(encoding="utf-8")
    )
    assert package["source"]["allow_unverified"] is True


def test_import_generates_source_metadata_for_git_package(tmp_path):
    paths = _project(tmp_path)
    buildroot = tmp_path / "buildroot"
    (buildroot / ".config").write_text("BR2_PACKAGE_GITFOO=y\n", encoding="utf-8")
    package_dir = buildroot / "package" / "gitfoo"
    package_dir.mkdir(parents=True)
    (package_dir / "gitfoo.mk").write_text(
        "GITFOO_VERSION = v1.2.3\n"
        "GITFOO_SITE = $(call github,example,gitfoo,$(GITFOO_VERSION))\n"
        "GITFOO_SITE_METHOD = git\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths, package="gitfoo")

    assert summary.failed == 0
    package = yaml.safe_load((tmp_path / "packages" / "gitfoo" / "package.yaml").read_text(encoding="utf-8"))
    assert package["source"] == {
        "type": "git",
        "url": "https://github.com/example/gitfoo.git",
        "commit": "v1.2.3",
        "local_files": ["sbuild.py"],
        "files": ["sbuild.py"],
    }
    config = package_source_config(paths, "gitfoo", load_description(tmp_path / "packages" / "gitfoo" / "package.yaml"))
    assert config.kind == "git"
    assert config.revision == "v1.2.3"


def test_import_uses_buildroot_default_source_for_github_site(tmp_path):
    paths = _project(tmp_path)
    buildroot = tmp_path / "buildroot"
    (buildroot / ".config").write_text("BR2_PACKAGE_GITHUBFOO=y\n", encoding="utf-8")
    package_dir = buildroot / "package" / "githubfoo"
    package_dir.mkdir(parents=True)
    (package_dir / "githubfoo.mk").write_text(
        "GITHUBFOO_VERSION = 1.2.3\n"
        "GITHUBFOO_SITE = $(call github,example,githubfoo,$(GITHUBFOO_VERSION))\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths, package="githubfoo")

    assert summary.failed == 0
    package = yaml.safe_load((tmp_path / "packages" / "githubfoo" / "package.yaml").read_text(encoding="utf-8"))
    assert package["source"]["url"] == "https://github.com/example/githubfoo/archive/1.2.3/githubfoo-1.2.3.tar.gz"
    assert package["source"]["archive"] == "githubfoo-1.2.3.tar.gz"


def test_import_uses_buildroot_gitlab_archive_path(tmp_path):
    paths = _project(tmp_path)
    buildroot = tmp_path / "buildroot"
    (buildroot / ".config").write_text("BR2_PACKAGE_GITLABFOO=y\n", encoding="utf-8")
    package_dir = buildroot / "package" / "gitlabfoo"
    package_dir.mkdir(parents=True)
    (package_dir / "gitlabfoo.mk").write_text(
        "GITLABFOO_VERSION = 1.2.3\n"
        "GITLABFOO_SITE = $(call gitlab,example,gitlabfoo,$(GITLABFOO_VERSION))\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths, package="gitlabfoo")

    assert summary.failed == 0
    package = yaml.safe_load((tmp_path / "packages" / "gitlabfoo" / "package.yaml").read_text(encoding="utf-8"))
    assert package["source"]["url"] == "https://gitlab.com/example/gitlabfoo/-/archive/1.2.3/gitlabfoo-1.2.3.tar.gz"


def test_import_uses_simple_buildroot_make_target(tmp_path):
    paths = _project(tmp_path)
    buildroot = tmp_path / "buildroot"
    (buildroot / ".config").write_text("BR2_PACKAGE_TARGETFOO=y\n", encoding="utf-8")
    package_dir = buildroot / "package" / "targetfoo"
    package_dir.mkdir(parents=True)
    (package_dir / "targetfoo.mk").write_text(
        "TARGETFOO_VERSION = 1.2.3\n"
        "TARGETFOO_SITE = https://example.org/targetfoo\n"
        "TARGETFOO_SOURCE = targetfoo-1.2.3.tar.gz\n"
        "define TARGETFOO_BUILD_CMDS\n"
        "\t$(TARGET_MAKE_ENV) $(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D) cross-compile\n"
        "endef\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths, package="targetfoo")

    assert summary.failed == 0
    script = (tmp_path / "packages" / "targetfoo" / "sbuild.py").read_text(encoding="utf-8")
    assert "commands.append([\"make\", 'cross-compile'])" in script


def test_import_does_not_collapse_multiple_buildroot_make_targets(tmp_path):
    paths = _project(tmp_path)
    buildroot = tmp_path / "buildroot"
    (buildroot / ".config").write_text("BR2_PACKAGE_MULTIFOO=y\n", encoding="utf-8")
    package_dir = buildroot / "package" / "multifoo"
    package_dir.mkdir(parents=True)
    (package_dir / "multifoo.mk").write_text(
        "MULTIFOO_VERSION = 1.2.3\n"
        "MULTIFOO_SITE = https://example.org/multifoo\n"
        "define MULTIFOO_BUILD_CMDS\n"
        "\t$(MAKE) -C $(@D) library tool helper $(TARGET_CONFIGURE_OPTS)\n"
        "endef\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths, package="multifoo")

    assert summary.failed == 0
    script = (tmp_path / "packages" / "multifoo" / "sbuild.py").read_text(encoding="utf-8")
    assert 'commands.append(["make"])' in script


def test_import_uses_tinyssh_install_layout(tmp_path):
    paths = _project(tmp_path)
    buildroot = tmp_path / "buildroot"
    (buildroot / ".config").write_text("BR2_PACKAGE_TINYSSH=y\n", encoding="utf-8")
    package_dir = buildroot / "package" / "tinyssh"
    package_dir.mkdir(parents=True)
    (package_dir / "tinyssh.mk").write_text(
        "TINYSSH_VERSION = 20240101\n"
        "TINYSSH_SITE = $(call github,janmojzis,tinyssh,$(TINYSSH_VERSION))\n"
        "define TINYSSH_BUILD_CMDS\n"
        "\t$(TARGET_MAKE_ENV) $(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D) cross-compile\n"
        "endef\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths, package="tinyssh")

    assert summary.failed == 0
    package = yaml.safe_load((tmp_path / "packages" / "tinyssh" / "package.yaml").read_text(encoding="utf-8"))
    assert package["build"]["python"]["outputs"] == ["/usr/sbin", "/usr/share/man"]
    assert package["install"]["path"] == "/usr/sbin/tinysshd"
    script = (tmp_path / "packages" / "tinyssh" / "sbuild.py").read_text(encoding="utf-8")
    assert "materialize_internal_symlinks(stage)" in script


def test_buildroot_menuconfig_uses_machine_work_output(tmp_path):
    paths = _project(tmp_path)
    calls = []

    def runner(command, cwd, env):
        calls.append((command, cwd))
        (paths.work_dir / "buildroot" / ".config").write_text("BR2_PACKAGE_FOO=y\n", encoding="utf-8")
        return type("Completed", (), {"returncode": 0})()

    result = run_buildroot_menuconfig(paths, command_runner=runner)
    assert result == paths.work_dir / "buildroot" / ".config"
    assert calls[0][0][-1] == "menuconfig"
    assert calls[0][1] == paths.work_dir / "buildroot-menuconfig-source"


def test_buildroot_menuconfig_clones_missing_tree_then_continues(tmp_path):
    paths = BuildPaths.for_machine("test-machine", root=tmp_path)
    calls = []

    def runner(command, cwd, env):
        calls.append(command)
        if command[:2] == ["git", "clone"]:
            clone_dir = Path(command[-1])
            clone_dir.mkdir(parents=True)
            (clone_dir / "Makefile").write_text("all:\n", encoding="utf-8")
            return type("Completed", (), {"returncode": 0})()
        (paths.work_dir / "buildroot" / ".config").parent.mkdir(parents=True, exist_ok=True)
        (paths.work_dir / "buildroot" / ".config").write_text("BR2_PACKAGE_FOO=y\n", encoding="utf-8")
        return type("Completed", (), {"returncode": 0})()

    result = run_buildroot_menuconfig(paths, command_runner=runner, confirm_runner=lambda path: True)

    assert result == paths.work_dir / "buildroot" / ".config"
    assert (tmp_path / "buildroot" / "Makefile").is_file()
    assert not (tmp_path / ".buildroot-clone").exists()
    assert calls[0][:4] == ["git", "clone", "--depth", "1"]
    assert calls[1][-1] == "menuconfig"


def test_buildroot_menuconfig_missing_tree_can_be_cancelled(tmp_path):
    paths = BuildPaths.for_machine("test-machine", root=tmp_path)

    with pytest.raises(SmartBuildError, match="clone was not confirmed"):
        run_buildroot_menuconfig(paths, confirm_runner=lambda path: False)


def test_buildroot_menuconfig_clone_failure_cleans_temporary_tree(tmp_path):
    paths = BuildPaths.for_machine("test-machine", root=tmp_path)

    def runner(command, cwd, env):
        clone_dir = Path(command[-1])
        clone_dir.mkdir(parents=True)
        (clone_dir / "partial").write_text("incomplete", encoding="utf-8")
        return type("Completed", (), {"returncode": 1})()

    with pytest.raises(SmartBuildError, match="failed to clone latest Buildroot"):
        run_buildroot_menuconfig(paths, command_runner=runner, confirm_runner=lambda path: True)
    assert not (tmp_path / ".buildroot-clone").exists()


def test_never_import_list_skips_libc_and_linux_packages(tmp_path):
    paths = _project(tmp_path)
    never_import = tmp_path / "packages" / ".imports"
    never_import.mkdir(parents=True)
    (never_import / "never-import.yaml").write_text(
        "schema_version: 1\npackages:\n  - glibc\n  - linux-headers\n  - musl\n",
        encoding="utf-8",
    )
    (tmp_path / "buildroot" / ".config").write_text(
        "BR2_PACKAGE_GLIBC=y\nBR2_PACKAGE_LINUX_HEADERS=y\nBR2_PACKAGE_FOO=y\n",
        encoding="utf-8",
    )
    (tmp_path / "buildroot" / "package" / "glibc").mkdir(parents=True)
    (tmp_path / "buildroot" / "package" / "glibc" / "glibc.mk").write_text(
        "GLIBC_VERSION = 2.39\nGLIBC_SITE = https://example.org/glibc\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths)
    statuses = {item.name: item.status for item in summary.items}

    assert statuses["glibc"] == "skipped"
    assert statuses["linux-headers"] == "skipped"
    assert statuses["foo"] == "success"
    assert not (tmp_path / "packages" / "glibc").exists()
    assert load_never_import_names(tmp_path) == frozenset({"glibc", "linux-headers", "musl"})
    ownership = yaml.safe_load(
        (tmp_path / "packages" / ".imports" / "buildroot-ownership.yaml").read_text(encoding="utf-8")
    )
    assert "BR2_PACKAGE_GLIBC" not in ownership.get("symbols", {})
    assert "BR2_PACKAGE_LINUX_HEADERS" not in ownership.get("symbols", {})


def test_never_import_list_skips_manually_removed_packages(tmp_path):
    paths = _project(tmp_path)
    never_import = tmp_path / "packages" / ".imports"
    never_import.mkdir(parents=True)
    (never_import / "never-import.yaml").write_text(
        "schema_version: 1\npackages:\n  - cmake\n  - valgrind\n",
        encoding="utf-8",
    )
    (tmp_path / "buildroot" / ".config").write_text(
        "BR2_PACKAGE_CMAKE=y\nBR2_PACKAGE_VALGRIND=y\nBR2_PACKAGE_FOO=y\n",
        encoding="utf-8",
    )

    summary = import_buildroot_packages(paths)
    statuses = {item.name: item.status for item in summary.items}

    assert statuses["cmake"] == "skipped"
    assert statuses["valgrind"] == "skipped"
    assert statuses["foo"] == "success"
    assert not (tmp_path / "packages" / "cmake").exists()
    assert not (tmp_path / "packages" / "valgrind").exists()


def test_ownership_write_drops_never_import_and_missing_packages(tmp_path):
    packages = tmp_path / "packages"
    packages.mkdir()
    (packages / "keep").mkdir()
    (packages / "keep" / "package.yaml").write_text(
        "schema_version: 1\nkind: package\nname: keep\nversion: '1.0'\n"
        "type: executable\nsource:\n  directory: apps/hello\n"
        "build:\n  python:\n    script: sbuild.py\n    outputs: [/bin/keep]\ninstall:\n  path: /bin/keep\n",
        encoding="utf-8",
    )
    never_import = packages / ".imports"
    never_import.mkdir()
    (never_import / "never-import.yaml").write_text(
        "schema_version: 1\npackages:\n  - musl\n  - cmake\n",
        encoding="utf-8",
    )
    (never_import / "buildroot-ownership.yaml").write_text(
        "symbols:\n"
        "  BR2_PACKAGE_KEEP:\n    owner: imported\n    package: keep\n"
        "  BR2_PACKAGE_MUSL:\n    owner: imported\n    package: musl\n"
        "  BR2_PACKAGE_CMAKE:\n    owner: native\n    package: cmake\n"
        "  BR2_PACKAGE_GONE:\n    owner: imported\n    package: gone\n",
        encoding="utf-8",
    )

    owners = _existing_owners(tmp_path)
    _write_ownership(tmp_path, owners, load_never_import_names(tmp_path))
    ownership = yaml.safe_load((never_import / "buildroot-ownership.yaml").read_text(encoding="utf-8"))
    symbols = ownership["symbols"]

    assert "BR2_PACKAGE_KEEP" in symbols
    assert "BR2_PACKAGE_MUSL" not in symbols
    assert "BR2_PACKAGE_CMAKE" not in symbols
    assert "BR2_PACKAGE_GONE" not in symbols


def test_repository_never_import_excludes_libc_linux_and_removed_packages():
    root = Path(__file__).resolve().parents[1]
    names = load_never_import_names(root)
    required = {
        "glibc",
        "musl",
        "uclibc",
        "uclibc-ng",
        "linux",
        "linux-headers",
        "cmake",
        "systemd",
        "bpftool",
        "flashrom",
        "gnu-efi",
        "gobject-introspection",
        "libcamera",
        "libseccomp",
        "libvirt",
        "ltrace",
        "openal",
        "perftest",
        "uftrace",
        "bitcoin",
        "libspdm",
        "swipl",
    }
    assert required.issubset(names)
    index = generate_package_kconfig_index(root)
    leftovers = []
    for name in sorted(names):
        if (root / "packages" / name).is_dir() or f"packages/{name}/" in index:
            leftovers.append(name)
    assert leftovers == []
    for name in (
        "ltp-testsuite",
        "oprofile",
        "luajit",
        "tensorflow-lite",
        "sedutil",
        "xnnpack",
        "cpuinfo",
        "fp16",
        "fxdiv",
        "psimd",
        "pthreadpool",
    ):
        assert (root / "packages" / name).is_dir()
    assert "xnnpack" not in names
    assert "cpuinfo" not in names


def test_repository_package_kconfigs_do_not_use_buildroot_label():
    root = Path(__file__).resolve().parents[1]
    labeled = []
    for path in (root / "packages").glob("*/Kconfig"):
        if "Buildroot import" in path.read_text(encoding="utf-8"):
            labeled.append(path.parent.name)
    assert labeled == []


def test_buildroot_menuconfig_restores_owned_package_selection(tmp_path):
    paths = _project(tmp_path)

    def runner(command, cwd, env):
        (paths.work_dir / "buildroot" / ".config").write_text(
            "# BR2_PACKAGE_EXISTING is not set\n", encoding="utf-8"
        )
        return type("Completed", (), {"returncode": 0})()

    result = run_buildroot_menuconfig(paths, command_runner=runner)
    assert "BR2_PACKAGE_EXISTING=y" in result.read_text(encoding="utf-8")
