schema_version: 1
kind: package
name: rosidl-runtime-cpp
version: 4.6.6
versions:
  - 4.6.6
default_version: 4.6.6
type: library
category: ROS 2
description: rosidl C++ runtime
depends:
  - rosidl-runtime-c
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rosidl-release/archive/release/jazzy/rosidl_runtime_cpp/4.6.6-1.tar.gz
  archive: rosidl_runtime_cpp-4.6.6-1.tar.gz
  sha256: f8c8870e941d672fcb6efbf3c01452b53fabe7337213245655f6c7cd697d0ab0
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/include
      - /usr/share
install:
  headers:
    - usr/include
