schema_version: 1
kind: package
name: iperf3
version: '3.21'
type: executable
description: iperf3 network bandwidth measurement tool
depends:
- openssl
source:
  type: archive
  url: https://downloads.es.net/pub/iperf/iperf-3.21.tar.gz
  archive: iperf-3.21.tar.gz
  strip_root: true
  allow_unverified: false
  sha256: 656e4405ebd620121de7ceca3eaf43a88f79ea1b857d041a6a0b1314801acdd8
  local_files:
  - sbuild.py
  files:
  - sbuild.py
build:
  python:
    script: sbuild.py
    outputs:
    - /usr/bin
    upstream_markers: []
install:
  path: /usr/bin/iperf3
