schema_version: 1
kind: package
name: rcpputils
version: 2.11.2
versions:
  - 2.11.2
default_version: 2.11.2
type: library
category: ROS 2
description: C++ utilities for ROS 2
depends:
  - rcutils
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rcpputils-release/archive/release/jazzy/rcpputils/2.11.2-1.tar.gz
  archive: rcpputils-2.11.2-1.tar.gz
  sha256: 0fb0871062ca47a0197a0586eb31a92f0b7316dbd4835263e212d07c68f66143
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/include
      - /usr/lib
      - /usr/share
install:
  headers:
    - usr/include
  libraries:
    - usr/lib
