schema_version: 1
kind: package
name: xnnpack
version: d7f398ee5e135ef4f7045802eea973cc6cb26c6c
type: executable
description: Neural network inference acceleration library
depends:
- cpuinfo
- fp16
- fxdiv
- pthreadpool
source:
  type: archive
  url: https://github.com/google/XNNPACK/archive/d7f398ee5e135ef4f7045802eea973cc6cb26c6c/xnnpack-d7f398ee5e135ef4f7045802eea973cc6cb26c6c.tar.gz
  archive: xnnpack-d7f398ee5e135ef4f7045802eea973cc6cb26c6c.tar.gz
  strip_root: true
  allow_unverified: false
  sha256: 0ed35a104a697abbae72b02b967e057883ff57b388178649c453b68cffb81f72
  local_files:
  - sbuild.py
  files:
  - sbuild.py
build:
  python:
    script: sbuild.py
    outputs:
    - /usr/bin
    upstream_markers: []
install:
  path: /usr/bin/xnnpack
