schema_version: 1
kind: package
name: type-description-interfaces
version: 2.0.4
versions:
  - 2.0.4
default_version: 2.0.4
type: library
category: ROS 2
description: ROS 2 type description message and service definitions
depends:
  - service-msgs
  - rosidl-default-runtime
host_depends:
  - ros2-host-sdk
source:
  type: archive
  url: https://github.com/ros2-gbp/rcl_interfaces-release/archive/refs/tags/release/jazzy/type_description_interfaces/2.0.4-1.tar.gz
  archive: type_description_interfaces-2.0.4-1.tar.gz
  sha256: 29c5d7f36c575efd3b8ed6609a4686dfa94841b4a70834c6cc89e98d19363512
  strip_root: true
  files:
    - CMakeLists.txt
    - package.xml
build:
  ament_cmake:
    testing: false
    linkage: shared
    host_python: sdk
    outputs:
      - /usr/include
      - /usr/lib
      - /usr/share
install:
  headers:
    - usr/include
  libraries:
    - usr/lib
