name: Manual Build Workflow

on:
  workflow_dispatch:
    inputs:
      machine:
        description: 'Target Machine'
        required: true
        type: choice
        options:
          - qemuarm64
          - qemuriscv64
        default: 'qemuarm64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gawk wget git diffstat unzip texinfo gcc build-essential \
            chrpath socat cpio python3 python3-pip python3-pexpect \
            xz-utils debianutils iputils-ping python3-git python3-jinja2 \
            libegl1-mesa libsdl1.2-dev python3-subunit mesa-common-dev \
            zstd liblz4-tool file locales
          sudo locale-gen en_US.UTF-8

      - name: Setup build environment
        run: |
          echo "Setting up build environment..."
          source ./smart-env
          echo "MACHINE=${{ github.event.inputs.machine }}" >> conf/local.conf

      - name: Build RT-Smart
        run: |
          source ./smart-env
          bitbake smart -c build_all

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.machine }}-build
          path: |
            build/${{ github.event.inputs.machine }}
            build/tmp/work/*/smart/*/temp/log.*
            build/tmp/log/cooker/* 