name: Manual Build Workflow

on:
  workflow_dispatch:
    inputs:
      machine:
        description: 'Target Machine'
        required: true
        type: choice
        options:
          - qemuarm64
          - qemuriscv64
        default: 'qemuarm64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get apt-get update && apt-get install -y sudo locales language-pack-en-base \
            chrpath cpio diffstat gawk lz4 wget zstd bash curl python3 pip bison flex file
          pip install requests scons kconfiglib tqdm --break-system-packages

          git clone https://github.com/openembedded/bitbake
          git clone https://github.com/openembedded/openembedded-core oe-core

      - name: Setup env & Build RT-Smart
        run: |
          source ./smart-env
          echo "MACHINE = \"${{ github.event.inputs.machine }}\"" >> conf/local.conf
          bitbake smart -c build_all

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.machine }}-build
          path: |
            ls build
            build/${{ github.event.inputs.machine }}
